const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Behaviors.Sin,
		C3.Behaviors.EightDir,
		C3.Behaviors.Platform,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Plugins.NinePatch,
		C3.Behaviors.scrollto,
		C3.Plugins.Particles,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.gamepad,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.Text.Acts.SetSize,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.PlayAtObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.gamepad.Cnds.CompareAxis,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.NinePatch.Acts.SetOpacity,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.Height,
		C3.JavaScriptInEvents.Accueil_Event1,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.JavaScriptInEvents.Accueil_Event7,
		C3.JavaScriptInEvents.Accueil_Event9,
		C3.JavaScriptInEvents.Accueil_Event11,
		C3.JavaScriptInEvents.Accueil_Event13,
		C3.JavaScriptInEvents.Accueil_Event15,
		C3.JavaScriptInEvents.Accueil_Event17,
		C3.Plugins.gamepad.Cnds.OnAnyButtonDown,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Audio.Acts.Stop,
		C3.JavaScriptInEvents.FinJeu1_Event11,
		C3.JavaScriptInEvents.FinJeu2_Event11,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Exps.Width,
		C3.JavaScriptInEvents.AnimationFinale_Event8,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Text.Acts.SetFontFace
	];
};
self.C3_JsPropNameTable = [
	{Solide: 0},
	{houseDark: 0},
	{houseDark6: 0},
	{Interpolation: 0},
	{Flash: 0},
	{houseDark7: 0},
	{Plateforme_New: 0},
	{Plateforme_New_End: 0},
	{Minuteur: 0},
	{Plateforme_New_Cassé: 0},
	{Sinus: 0},
	{Plateforme_New_Bouge: 0},
	{houseDark2: 0},
	{Help_End: 0},
	{"8Directions": 0},
	{Fusée_Jeu_1: 0},
	{Transition1: 0},
	{Plateforme: 0},
	{Fusée_Jeu_2: 0},
	{Fusée_Jeu_3: 0},
	{UI: 0},
	{UI2: 0},
	{VieAlien: 0},
	{Projectile: 0},
	{Sprite: 0},
	{Animation_Fusée_Détruite1: 0},
	{Animation_Fusée_Détruite2: 0},
	{Animation_Fusée_Détruite3: 0},
	{Animation_Fusée_Détruite4: 0},
	{Animation_Fusée_Détruite5: 0},
	{Transition_Jeu_2_1: 0},
	{Transition_Jeu_2_2: 0},
	{Transition_Jeu_2_3: 0},
	{Fusée_Jeu_1_Débutant: 0},
	{Continuer: 0},
	{Texte_Chrono_Labyrinthe: 0},
	{Texte: 0},
	{Texte2: 0},
	{Fondu: 0},
	{Texte3: 0},
	{Texte4: 0},
	{TexteAvantAcceuil: 0},
	{Titre: 0},
	{TexteAideBouton: 0},
	{FREDERICPLATEUS: 0},
	{MISSION13: 0},
	{MISSION23: 0},
	{MISSION33: 0},
	{MISSIONREUSSIE13: 0},
	{MISSIONREUSSIE23: 0},
	{Texte5: 0},
	{MISSIONREUSSIE33: 0},
	{TexteDecollageImminent: 0},
	{TexteCompteRebours: 0},
	{FELICITATIONS: 0},
	{TexteAideBouton2: 0},
	{ErreurBouton: 0},
	{TexteCheatCode: 0},
	{Difficulté: 0},
	{Texte_Aliens_Restants: 0},
	{"9patch": 0},
	{"9patch2": 0},
	{Acceuil: 0},
	{BGJeu: 0},
	{BGJeu2: 0},
	{Bonus_Carburant: 0},
	{Bullet: 0},
	{DéfilerVers: 0},
	{Cam_Niv3: 0},
	{Curseur: 0},
	{Ellipse: 0},
	{f6b0feda39f4e28aeaa28abe97074e: 0},
	{FadeToBlack: 0},
	{flagGreen_up: 0},
	{Flèche: 0},
	{Flèche2: 0},
	{image: 0},
	{Jeu: 0},
	{Jouez: 0},
	{Obj_Camera: 0},
	{Particules_Bleue: 0},
	{Scène: 0},
	{Scène2: 0},
	{Scène3: 0},
	{Scène4: 0},
	{Scène5: 0},
	{Silver_Rocket: 0},
	{Souris: 0},
	{Transition: 0},
	{Transition2: 0},
	{Transition3: 0},
	{Untitled: 0},
	{Untitled2: 0},
	{BGJeu3: 0},
	{BGJeu4: 0},
	{UI_Difficultés: 0},
	{Particules_Blanche: 0},
	{Clavier: 0},
	{JoyCon: 0},
	{Flamme: 0},
	{LignesVitesse: 0},
	{FlashFinal: 0},
	{Animation_Intro: 0},
	{YXr0vo: 0},
	{Audio: 0},
	{numeroCoeur: 0},
	{HUD_Coeur: 0},
	{hud_temps_fill: 0},
	{PlanDeTravail2: 0},
	{texte_deco_temps: 0},
	{TXT_Temps: 0},
	{HUD_Barre_Doodle: 0},
	{PlanDeTravail: 0},
	{HUD_Fusee_Doodle: 0},
	{HUD_Ennemi_fond: 0},
	{numeroSegment: 0},
	{HUD_Ennemi_Segment: 0},
	{TXT_Ennemis: 0},
	{TempsLabyrinthe: 0},
	{JeuActif: 0},
	{AideBoutonDirecte: 0},
	{DépartJeu1x: 0},
	{DépartJeu1y: 0},
	{Respawn: 0},
	{CompteurMort: 0},
	{doodleYDepart: 0},
	{doodleHauteurObjectif: 0},
	{hudBarreBasY: 0},
	{hudBarreHauteur: 0},
	{progressionDoodle: 0},
	{EtapeDialogue: 0},
	{Intro_Lance: 0},
	{AideBoutonTimer: 0},
	{AideBoutonVisible: 0},
	{AideBoutonActive: 0},
	{SceneRetour: 0},
	{EtapeDialogue2: 0},
	{EtapeDialogue3: 0},
	{CompteRebours: 0},
	{EtatFin: 0},
	{ErreurBoutonOn: 0},
	{TempsLabyrinthe2: 0},
	{JeuActif2: 0},
	{AideBoutonDirecte2: 0},
	{DépartJeu1x2: 0},
	{DépartJeu1y2: 0},
	{Respawn2: 0},
	{tempsMax2: 0},
	{tempsActuel2: 0},
	{largeurMaxTemps2: 0},
	{viesActuelles2: 0},
	{TempsLabyrinthe4: 0},
	{JeuActif4: 0},
	{AideBoutonDirecte4: 0},
	{DépartJeu1x4: 0},
	{DépartJeu1y4: 0},
	{Respawn4: 0},
	{tempsMax3: 0},
	{tempsActuel3: 0},
	{largeurMaxTemps3: 0},
	{viesActuelles3: 0},
	{doodleYDepart3: 0},
	{doodleHauteurObjectif3: 0},
	{hudBarreBasY3: 0},
	{hudBarreHauteur3: 0},
	{progressionDoodle3: 0},
	{doodleYDepart2: 0},
	{doodleHauteurObjectif2: 0},
	{hudBarreBasY2: 0},
	{hudBarreHauteur2: 0},
	{progressionDoodle2: 0},
	{compterEnnemis: 0},
	{CompteurMort2: 0},
	{ennemisTotal: 0},
	{ennemisRestants: 0},
	{CompteurMort3: 0},
	{compterEnnemis2: 0},
	{ennemisTotal2: 0},
	{ennemisRestants2: 0},
	{TempsLabyrinthe5: 0},
	{JeuActif5: 0},
	{AideBoutonDirecte5: 0},
	{DépartJeu1x5: 0},
	{DépartJeu1y5: 0},
	{Respawn5: 0},
	{ToucheMur: 0},
	{PeutToucherMur: 0},
	{tempsMax: 0},
	{tempsActuel: 0},
	{largeurMaxTemps: 0},
	{viesActuelles: 0},
	{CompteurMort5: 0},
	{compterEnnemis3: 0},
	{ennemisTotal3: 0},
	{ennemisRestants3: 0}
];

self.InstanceType = {
	houseDark: class extends self.ISpriteInstance {},
	houseDark6: class extends self.ISpriteInstance {},
	Flash: class extends self.ISpriteInstance {},
	houseDark7: class extends self.ISpriteInstance {},
	Plateforme_New: class extends self.ISpriteInstance {},
	Plateforme_New_End: class extends self.ISpriteInstance {},
	Plateforme_New_Cassé: class extends self.ISpriteInstance {},
	Plateforme_New_Bouge: class extends self.ISpriteInstance {},
	houseDark2: class extends self.ISpriteInstance {},
	Help_End: class extends self.ISpriteInstance {},
	Fusée_Jeu_1: class extends self.ISpriteInstance {},
	Transition1: class extends self.ISpriteInstance {},
	Fusée_Jeu_2: class extends self.ISpriteInstance {},
	Fusée_Jeu_3: class extends self.ISpriteInstance {},
	UI: class extends self.ISpriteInstance {},
	UI2: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Animation_Fusée_Détruite1: class extends self.ISpriteInstance {},
	Animation_Fusée_Détruite2: class extends self.ISpriteInstance {},
	Animation_Fusée_Détruite3: class extends self.ISpriteInstance {},
	Animation_Fusée_Détruite4: class extends self.ISpriteInstance {},
	Animation_Fusée_Détruite5: class extends self.ISpriteInstance {},
	Transition_Jeu_2_1: class extends self.ISpriteInstance {},
	Transition_Jeu_2_2: class extends self.ISpriteInstance {},
	Transition_Jeu_2_3: class extends self.ISpriteInstance {},
	Fusée_Jeu_1_Débutant: class extends self.ISpriteInstance {},
	Continuer: class extends self.ITextInstance {},
	Texte_Chrono_Labyrinthe: class extends self.ITextInstance {},
	Texte: class extends self.ITextInstance {},
	Texte2: class extends self.ITextInstance {},
	Texte3: class extends self.ITextInstance {},
	Texte4: class extends self.ITextInstance {},
	TexteAvantAcceuil: class extends self.ITextInstance {},
	Titre: class extends self.ITextInstance {},
	TexteAideBouton: class extends self.ITextInstance {},
	FREDERICPLATEUS: class extends self.ITextInstance {},
	MISSION13: class extends self.ITextInstance {},
	MISSION23: class extends self.ITextInstance {},
	MISSION33: class extends self.ITextInstance {},
	MISSIONREUSSIE13: class extends self.ITextInstance {},
	MISSIONREUSSIE23: class extends self.ITextInstance {},
	Texte5: class extends self.ITextInstance {},
	MISSIONREUSSIE33: class extends self.ITextInstance {},
	TexteDecollageImminent: class extends self.ITextInstance {},
	TexteCompteRebours: class extends self.ITextInstance {},
	FELICITATIONS: class extends self.ITextInstance {},
	TexteAideBouton2: class extends self.ITextInstance {},
	ErreurBouton: class extends self.ITextInstance {},
	TexteCheatCode: class extends self.ITextInstance {},
	Difficulté: class extends self.ITextInstance {},
	Texte_Aliens_Restants: class extends self.ITextInstance {},
	_9patch: class extends self.I9PatchInstance {},
	_9patch2: class extends self.I9PatchInstance {},
	Acceuil: class extends self.ISpriteInstance {},
	BGJeu: class extends self.ISpriteInstance {},
	BGJeu2: class extends self.ISpriteInstance {},
	Bonus_Carburant: class extends self.ISpriteInstance {},
	Bullet: class extends self.ISpriteInstance {},
	Cam_Niv3: class extends self.ISpriteInstance {},
	Curseur: class extends self.ISpriteInstance {},
	Ellipse: class extends self.ISpriteInstance {},
	f6b0feda39f4e28aeaa28abe97074e: class extends self.ISpriteInstance {},
	FadeToBlack: class extends self.ISpriteInstance {},
	flagGreen_up: class extends self.ISpriteInstance {},
	Flèche: class extends self.ISpriteInstance {},
	Flèche2: class extends self.ISpriteInstance {},
	image: class extends self.ISpriteInstance {},
	Jeu: class extends self.ISpriteInstance {},
	Jouez: class extends self.ISpriteInstance {},
	Obj_Camera: class extends self.ISpriteInstance {},
	Particules_Bleue: class extends self.IParticlesInstance {},
	Scène: class extends self.ISpriteInstance {},
	Scène2: class extends self.ISpriteInstance {},
	Scène3: class extends self.ISpriteInstance {},
	Scène4: class extends self.ISpriteInstance {},
	Scène5: class extends self.ISpriteInstance {},
	Silver_Rocket: class extends self.ISpriteInstance {},
	Souris: class extends self.IInstance {},
	Transition: class extends self.ISpriteInstance {},
	Transition2: class extends self.ISpriteInstance {},
	Transition3: class extends self.ISpriteInstance {},
	Untitled: class extends self.ISpriteInstance {},
	Untitled2: class extends self.ISpriteInstance {},
	BGJeu3: class extends self.ISpriteInstance {},
	BGJeu4: class extends self.ISpriteInstance {},
	UI_Difficultés: class extends self.ISpriteInstance {},
	Particules_Blanche: class extends self.IParticlesInstance {},
	Clavier: class extends self.IInstance {},
	JoyCon: class extends self.IInstance {},
	Flamme: class extends self.ISpriteInstance {},
	LignesVitesse: class extends self.ISpriteInstance {},
	FlashFinal: class extends self.ISpriteInstance {},
	Animation_Intro: class extends self.ISpriteInstance {},
	YXr0vo: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	HUD_Coeur: class extends self.ISpriteInstance {},
	hud_temps_fill: class extends self.ISpriteInstance {},
	PlanDeTravail2: class extends self.ISpriteInstance {},
	texte_deco_temps: class extends self.ITextInstance {},
	TXT_Temps: class extends self.ITextInstance {},
	HUD_Barre_Doodle: class extends self.ISpriteInstance {},
	PlanDeTravail: class extends self.ISpriteInstance {},
	HUD_Fusee_Doodle: class extends self.ISpriteInstance {},
	HUD_Ennemi_fond: class extends self.ISpriteInstance {},
	HUD_Ennemi_Segment: class extends self.ISpriteInstance {},
	TXT_Ennemis: class extends self.ITextInstance {}
}